# Generated by Django 5.0.6 on 2024-05-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
